export const socialForm = [
  {
    name: 'twitter',
    link: 'https://twitter.com/',
    icon: 'https://cdn.jsdelivr.net/npm/simple-icons@v3/icons/twitter.svg',
    shields: 'https://img.shields.io/badge/twitter-x?style=for-the-badge&logo=x&logoColor=white&color=%230f1419',
    placeholder: 'twitter profile url',
  },
  {
    name: 'youtube',
    link: 'https://www.youtube.com/',
    icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/youtube.svg',
    shields: 'https://img.shields.io/badge/youtube-logo?style=for-the-badge&logo=youtube&logoColor=white&color=%23cc0000',
    placeholder: 'youtube profile url',
  },
  {
    name: 'linkedin',
    link: 'https://www.linkedin.com/in/',
    icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/linkedin.svg',
    shields: 'https://img.shields.io/badge/linkedin-logo?style=for-the-badge&logo=linkedin&logoColor=white&color=%230a77b6',
    placeholder: 'linkedin profile url',
  },
  {
    name: 'stackoverflow',
    link: 'https://stackoverflow.com/users/',
    icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/stackoverflow.svg',
    shields: 'https://img.shields.io/badge/stackoverflow-logo?style=for-the-badge&logo=stackoverflow&logoColor=white&color=%23cc0000',
    placeholder: 'stackoverflow profile url',
  },
  {
    name: 'medium',
    link: 'https://medium.com/',
    icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/medium.svg',
    shields: 'https://img.shields.io/badge/medium-logo?style=for-the-badge&logo=medium&logoColor=white&color=black',
    placeholder: 'medium profile url',
  },
  {
    name: 'dev.to',
    link: 'https://dev.to/',
    icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/dev-dot-to.svg',
    shields: 'https://img.shields.io/badge/dev-to?style=for-the-badge&logo=dev-to&logoColor=white&color=black',
    placeholder: 'dev.to profile url',
  },
  {
    name: 'codepen',
    link: 'https://www.codepen.io/',
    icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/codepen.svg',
    shields: 'https://img.shields.io/badge/Codepen-000000?style=for-the-badge&logo=codepen&logoColor=white',
    placeholder: 'codepen profile url',
  },
  {
    name: 'codesandbox',
    link: 'https://codesandbox.com/u/',
    icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/codesandbox.svg',
    shields: 'https://img.shields.io/badge/Codesandbox-000000?style=for-the-badge&logo=CodeSandbox&logoColor=white',
    placeholder: 'codesandbox profile url',
  },
  {
    name: 'facebook',
    link: 'https://www.facebook.com/',
    icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/facebook.svg',
    shields: 'https://img.shields.io/badge/facebook-logo?style=for-the-badge&logo=facebook&logoColor=white&color=%230866ff',
    placeholder: 'facebook profile url',
  },
  {
    name: 'instagram',
    link: 'https://www.instagram.com/',
    icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/instagram.svg',
    shields: 'https://img.shields.io/badge/instagram-logo?style=for-the-badge&logo=instagram&logoColor=white&color=%23F35369',
    placeholder: 'instagram profile url',
  },
  {
    name: 'dribbble',
    link: 'https://www.dribbble.com/',
    icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/dribbble.svg',
    shields: 'https://img.shields.io/badge/dribbble-logo?style=for-the-badge&logo=dribbble&logoColor=white&color=%23ea64d9',
    placeholder: 'dribbble profile url',
  },
  {
    name: 'behance',
    link: 'https://www.behance.net/',
    icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/behance.svg',
    shields: 'https://img.shields.io/badge/behance-logo?style=for-the-badge&logo=behance&logoColor=white&color=%230057ff',
    placeholder: 'behance profile url',
  },
  {
    name: '掘金',
    link: 'https://www.juejin.cn/',
    icon: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsPSJjdXJyZW50Q29sb3IiIGQ9Im0xMiAxNC4zMTZsNy40NTQtNS44OGwtMi4wMjItMS42MjVMMTIgMTEuMWwtLjAwNC4wMDNsLTUuNDMyLTQuMjg4bC0yLjAyIDEuNjI0bDcuNDUyIDUuODhabTAtNy4yNDdsMi44OS0yLjI5OEwxMiAyLjQ1M2wtLjAwNC0uMDA1bC0yLjg4NCAyLjMxOGwyLjg4NCAyLjNabTAgMTEuMjY2bC0uMDA1LjAwMmwtOS45NzUtNy44N0wwIDEyLjA4OGwuMTk0LjE1NmwxMS44MDMgOS4zMDhsNy40NjMtNS44ODVMMjQgMTIuMDg1bC0yLjAyMy0xLjYyNFoiLz48L3N2Zz4=',
    shields: 'https://img.shields.io/static/v1?style=for-the-badge&message=Juejin&color=007FFF&logo=Juejin&logoColor=FFFFFF&label=',
    placeholder: 'JueJin profile url',
  },
  {
    name: '知乎',
    link: 'https://www.zhihu.com/',
    icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/zhihu.svg',
    shields: 'https://img.shields.io/badge/zhihu-%230084FF.svg?&style=for-the-badge&logo=zhihu&logoColor=white',
    placeholder: 'ZhiHu profile url',
  },
  {
    name: 'Wei Bo',
    link: 'https://www.weibo.com/',
    icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/sinaweibo.svg',
    shields: 'https://img.shields.io/badge/sina%20weibo-%23E6162D.svg?&style=for-the-badge&logo=sina%20weibo&logoColor=white',
    placeholder: 'WeiBo profile url',
  },
  {
    name: 'weChat',
    link: 'https://githubbio.com/weChat/',
    icon: 'https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/wechat.svg',
    shields: 'https://img.shields.io/badge/WeChat-07C160?style=for-the-badge&logo=wechat&logoColor=white',
    placeholder: 'weChat name/id',
  }
]